=== kennethkutyn-optimizely/flappy-flags/src/modules/app-code/step1/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "type": {
      "type": "string"
    },
    "start": {
      "type": "integer"
    },
    "end": {
      "type": "integer"
    },
    "body": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "start": {
              "type": "integer"
            },
            "end": {
              "type": "integer"
            },
            "expression": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "start": {
                  "type": "integer"
                },
                "end": {
                  "type": "integer"
                },
                "operator": {
                  "type": "string"
                },
                "left": {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string"
                    },
                    "start": {
                      "type": "integer"
                    },
                    "end": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "type",
                    "start",
                    "end",
                    "name"
                  ]
                },
                "right": {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string"
                    },
                    "start": {
                      "type": "integer"
                    },
                    "end": {
                      "type": "integer"
                    },
                    "properties": {
                      "type": "array",
                      "items": [
                        {
                          "type": "object",
                          "properties": {
                            "type": {
                              "type": "string"
                            },
                            "start": {
                              "type": "integer"
                            },
                            "end": {
                              "type": "integer"
                            },
                            "method": {
                              "type": "boolean"
                            },
                            "shorthand": {
                              "type": "boolean"
                            },
                            "computed": {
                              "type": "boolean"
                            },
                            "key": {
                              "type": "object",
                              "properties": {
                                "type": {
                                  "type": "string"
                                },
                                "start": {
                                  "type": "integer"
                                },
                                "end": {
                                  "type": "integer"
                                },
                                "name": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "type",
                                "start",
                                "end",
                                "name"
                              ]
                            },
                            "value": {
                              "type": "object",
                              "properties": {
                                "type": {
                                  "type": "string"
                                },
                                "start": {
                                  "type": "integer"
                                },
                                "end": {
                                  "type": "integer"
                                },
                                "value": {
                                  "type": "boolean"
                                },
                                "raw": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "type",
                                "start",
                                "end",
                                "value",
                                "raw"
                              ]
                            },
                            "kind": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "type",
                            "start",
                            "end",
                            "method",
                            "shorthand",
                            "computed",
                            "key",
                            "value",
                            "kind"
                          ]
                        },
                        {
                          "type": "object",
                          "properties": {
                            "type": {
                              "type": "string"
                            },
                            "start": {
                              "type": "integer"
                            },
                            "end": {
                              "type": "integer"
                            },
                            "method": {
                              "type": "boolean"
                            },
                            "shorthand": {
                              "type": "boolean"
                            },
                            "computed": {
                              "type": "boolean"
                            },
                            "key": {
                              "type": "object",
                              "properties": {
                                "type": {
                                  "type": "string"
                                },
                                "start": {
                                  "type": "integer"
                                },
                                "end": {
                                  "type": "integer"
                                },
                                "name": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "type",
                                "start",
                                "end",
                                "name"
                              ]
                            },
                            "value": {
                              "type": "object",
                              "properties": {
                                "type": {
                                  "type": "string"
                                },
                                "start": {
                                  "type": "integer"
                                },
                                "end": {
                                  "type": "integer"
                                },
                                "value": {
                                  "type": "number"
                                },
                                "raw": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "type",
                                "start",
                                "end",
                                "value",
                                "raw"
                              ]
                            },
                            "kind": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "type",
                            "start",
                            "end",
                            "method",
                            "shorthand",
                            "computed",
                            "key",
                            "value",
                            "kind"
                          ]
                        }
                      ]
                    }
                  },
                  "required": [
                    "type",
                    "start",
                    "end",
                    "properties"
                  ]
                }
              },
              "required": [
                "type",
                "start",
                "end",
                "operator",
                "left",
                "right"
              ]
            }
          },
          "required": [
            "type",
            "start",
            "end",
            "expression"
          ]
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "start": {
              "type": "integer"
            },
            "end": {
              "type": "integer"
            },
            "expression": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "start": {
                  "type": "integer"
                },
                "end": {
                  "type": "integer"
                },
                "callee": {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string"
                    },
                    "start": {
                      "type": "integer"
                    },
                    "end": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "type",
                    "start",
                    "end",
                    "name"
                  ]
                },
                "arguments": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "type": {
                          "type": "string"
                        },
                        "start": {
                          "type": "integer"
                        },
                        "end": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "type",
                        "start",
                        "end",
                        "name"
                      ]
                    }
                  ]
                }
              },
              "required": [
                "type",
                "start",
                "end",
                "callee",
                "arguments"
              ]
            }
          },
          "required": [
            "type",
            "start",
            "end",
            "expression"
          ]
        }
      ]
    },
    "sourceType": {
      "type": "string"
    }
  },
  "required": [
    "type",
    "start",
    "end",
    "body",
    "sourceType"
  ]
}

=== kennethkutyn-optimizely/flappy-flags/src/modules/app-code/step1/ast.json
{
  "type": "Program",
  "start": 0,
  "end": 84,
  "body": [
    {
      "type": "ExpressionStatement",
      "start": 15,
      "end": 58,
      "expression": {
        "type": "AssignmentExpression",
        "start": 15,
        "end": 58,
        "operator": "=",
        "left": {
          "type": "Identifier",
          "start": 15,
          "end": 21,
          "name": "config"
        },
        "right": {
          "type": "ObjectExpression",
          "start": 24,
          "end": 58,
          "properties": [
            {
              "type": "Property",
              "start": 28,
              "end": 39,
              "method": false,
              "shorthand": false,
              "computed": false,
              "key": {
                "type": "Identifier",
                "start": 28,
                "end": 33,
                "name": "pipes"
              },
              "value": {
                "type": "Literal",
                "start": 35,
                "end": 39,
                "value": true,
                "raw": "true"
              },
              "kind": "init"
            },
            {
              "type": "Property",
              "start": 43,
              "end": 55,
              "method": false,
              "shorthand": false,
              "computed": false,
              "key": {
                "type": "Identifier",
                "start": 43,
                "end": 50,
                "name": "gravity"
              },
              "value": {
                "type": "Literal",
                "start": 52,
                "end": 55,
                "value": 9.8,
                "raw": "9.8"
              },
              "kind": "init"
            }
          ]
        }
      }
    },
    {
      "type": "ExpressionStatement",
      "start": 60,
      "end": 83,
      "expression": {
        "type": "CallExpression",
        "start": 60,
        "end": 83,
        "callee": {
          "type": "Identifier",
          "start": 60,
          "end": 75,
          "name": "startFlappyBird"
        },
        "arguments": [
          {
            "type": "Identifier",
            "start": 76,
            "end": 82,
            "name": "config"
          }
        ]
      }
    }
  ],
  "sourceType": "module"
}
